In [2]:
import numpy as np
##np is an alias

In [3]:
lst=[1,2,3.3,4]
arr=np.array(lst)

In [4]:
arr.shape

(4,)

In [16]:
type(arr)

numpy.ndarray

In [17]:
##above one is n dimensional array

In [18]:
lst1=[1,2,3,4,5]
lst2=[3,4,5,6,69]
lst3=[7,8,9,69,69]

arr1=np.array([lst1,lst2,lst3])

In [19]:
arr1.shape
##rows , column

(3, 5)

In [20]:
arr

array([1. , 2. , 3.3, 4. ])

In [21]:
arr[3]

np.float64(4.0)

In [22]:
arr[3]=5

In [23]:
arr


array([1. , 2. , 3.3, 5. ])

In [24]:
arr[1:]

array([2. , 3.3, 5. ])

In [25]:
arr[1:3]


array([2. , 3.3])

In [26]:
arr[-1]

np.float64(5.0)

In [27]:
arr[:-1]

array([1. , 2. , 3.3])

In [28]:
arr[::-1]

array([5. , 3.3, 2. , 1. ])

In [29]:
arr[::-3]

array([5., 1.])

In [30]:
arr[::-2]

array([5., 2.])

In [31]:
arr1


array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6, 69],
       [ 7,  8,  9, 69, 69]])

In [32]:
arr1[:,1]

array([2, 4, 8])

In [33]:
arr1[1,:]

array([ 3,  4,  5,  6, 69])

In [34]:
arr1[0,:]

array([1, 2, 3, 4, 5])

In [35]:
arr1[1:,1:3]

array([[4, 5],
       [8, 9]])

In [36]:
arr1[0:2,2:4].shape

(2, 2)

In [37]:
arr1[::-2,0:]

array([[ 7,  8,  9, 69, 69],
       [ 1,  2,  3,  4,  5]])

In [38]:
arr


array([1. , 2. , 3.3, 5. ])

In [39]:
arr<2

array([ True, False, False, False])

In [40]:
arr[arr<2]

array([1.])

In [41]:
arr1.shape


(3, 5)

In [42]:
## interchanging the rows with columns 
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  3],
       [ 4,  5,  6],
       [69,  7,  8],
       [ 9, 69, 69]])

In [43]:
## 1 more mechanism to create an array 
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [44]:
## we can reshape in any manner but the product should be equal to the no. of elements 
np.arange(1,30,2).reshape(3,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [45]:
np.arange(1,30,2).reshape(15,1)

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19],
       [21],
       [23],
       [25],
       [27],
       [29]])

In [50]:
np.arange(1,30,2).reshape(3,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]],

       [[21],
        [23],
        [25],
        [27],
        [29]]])

In [52]:
arr*arr

array([ 1.  ,  4.  , 10.89, 25.  ])

In [55]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 3,  4,  5,  6, 69],
       [ 7,  8,  9, 69, 69]])

In [57]:
arr1*arr1

array([[   1,    4,    9,   16,   25],
       [   9,   16,   25,   36, 4761],
       [  49,   64,   81, 4761, 4761]])

In [59]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.zeros((10,10,10))

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]

In [72]:
np.random.randint(10,50)

40

In [77]:
np.random.randint(10,50,50)

array([24, 32, 19, 37, 39, 19, 34, 22, 41, 47, 24, 45, 11, 35, 48, 44, 22,
       13, 48, 46, 22, 40, 46, 44, 48, 32, 48, 33, 20, 20, 21, 10, 23, 24,
       34, 42, 49, 44, 44, 37, 19, 49, 24, 35, 41, 17, 42, 19, 31, 20],
      dtype=int32)

In [84]:
np.random.randint(10,50,4).reshape(2,2)

array([[12, 46],
       [35, 34]], dtype=int32)

In [87]:
## DONT KNOW
np.random.randn(5,6)

array([[ 0.23209782,  0.45446065, -0.31347687, -0.55088902, -0.30911261,
        -0.92030167],
       [-0.01260035, -0.08647632,  0.30729078, -1.07479057,  1.08949877,
         0.80121848],
       [-0.08902756, -0.86098162, -0.08225356, -1.3423778 , -0.72978345,
         0.78212387],
       [-0.71313576, -0.12415139,  2.45900894,  1.80186257,  0.31660241,
         0.23849604],
       [ 0.08265547, -0.13457594,  0.10110478,  1.06702316,  0.13006233,
         2.01096267]])

In [89]:
## TAKES RANDOM N0. FROM 0 TO 1
np.random.random_sample((4,4))

array([[0.64895932, 0.86967603, 0.99678533, 0.9247621 ],
       [0.62029322, 0.5891258 , 0.01036847, 0.01583414],
       [0.62800998, 0.463873  , 0.51890533, 0.67218594],
       [0.38846076, 0.51916442, 0.58323357, 0.78516953]])